baseURL = "http://example.org/"
languageCode = "en-us"

pygmentsCodeFences = true
title = "Christoph Hartmann"

paginate = 20
canonifyurls = true

theme = "hugo-coder"

[params]
    author = "Christoph Hartmann"
    info = "Founder, Tech leader,<br>Co-Creator of <a href=\"https://inspec.io\">InSpec</a> and <a href=\"https://dev-sec.io/\">DevSec</a>."
    description = "Chris's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/chris.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    rtl = false
    math = true


[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/chris-rock/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/chrihartmann"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/chri_hartmann"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Talks"
    weight = 2
    url = "/talks/"